### ISSUE TITLE
LIFF JavaScript SDK - login parameter redirectUri not working

### ISSUE THREAD

**Issue by terrylinooo** [line/line-liff-v2-starter#66]
LIFF JavaScript SDK - login parameter redirectUri not working as expected.

Everytime I set the redirectUri always get `liff.isLoggedIn()` returned false.

The endpoint is the website's domain, ex, `https://www.example.com`
The redirectUri I set is at the same dmain but a path, ex, `https://www.example.com/checkout/`

**Describe the bug**

Not working.
```
liff.login({
   redirectUri: window.location.href,
});
```

Working
```
liff.login();

// or

liff.login({
   redirectUri: `100% fit to the the endpoint URL`,
});
```
**Expected behavior**
The login status is supposed to be true after redirecting back to the website.

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version: Almost tried many different SDK version from 2.3 to 2.21.2

**Comment by kazuma0129** [comment]
@terrylinooo 
Thank you for creating the issue. We apologize for the delay in responding.

We believe that this issue is related to the LIFF SDK and LINE Login specifications. We are very sorry, but this repository does not provide such technical support, and we are only receiving content limited to line-liff-v2-starter. Therefore, we will close this issue as unsupported.
Thank you.
